version: '2'
services:
  tws:
    build: .
    ports:
      - "4003:4003"
      - "5901:5900"
    volumes:
      - ./ib/IBController.ini:/root/IBController/IBController.ini
      - ./ib/jts.ini:/root/Jts/jts.ini
    environment:
      - TZ=Asia/Hong_Kong
      # Variables pulled from /IBController/IBControllerGatewayStart.sh
      - VNC_PASSWORD=1234 # CHANGEME
      - TWS_MAJOR_VRSN=1022
      - IBC_INI=/root/IBController/IBController.ini
      - IBC_PATH=/opt/IBController
      - TWS_PATH=/root/Jts
      - TWS_CONFIG_PATH=/root/Jts
      - LOG_PATH=/opt/IBController/Logs
      - JAVA_PATH=/usr/local/openjdk-8/bin # JRE is bundled starting with TWS 952 
      - TRADING_MODE=paper # either paper or live
      - TWSUSERID= # IB account
      - TWSPASSWORD= # IB account password
      - FIXUSERID=
      - FIXPASSWORD=
      - APP=GATEWAY